src/components/signup/SignUp.jsx

[병합] 중간피드백 반영  

---

src/components/login/Login.jsx

[Login.jsx] test

---

src/components/login/Login.jsx

[develop] test

---

netlify.toml

[netlify.toml] http 요청 https로 리디렉션 코드 추가

[netlify.toml] http 요청 https로 리디렉션 코드 추가

---

src/components/signup/SignUp.jsx

[SignUp.jsx] http:/ -> http:// 로 수정

[SignUp.jsx] http:/ -> http:// 로 수정

---

functions/yourFunction.js
netlify.toml

[netlify] https -> http 서버 연결

---

src/components/signup/SignUp.jsx

[SignUp.jsx] 성별 value값 영문으로 변경

[SignUp.jsx] 성별 value값 영문으로 변경

---

src/components/signup/SignUp.jsx

[SignUp.jsx] json -> 문자열로 요청보내기

[SignUp.jsx] json -> 문자열로 요청보내기

---

src/components/signup/SignUp.jsx

[SignUp.jsx] fetch -> axios로 변경

[SignUp.jsx] fetch -> axios로 변경

---

src/components/signup/SignUp.jsx

[SignUp.jsx] json 형식으로 전송 코드 추가 및 에러처리 세분화

[SignUp.jsx] json 형식으로 전송 코드 추가 및 에러처리 세분화

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] 데이터 보내는 코드 추가

[ProductAddPage.jsx] 데이터 보내는 코드 추가

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] 로그인시 이메일 seller로 넘기기

[ProductAddPage.jsx] 로그인시 이메일 seller로 넘기기

---

src/components/add-product/AddPeriod.jsx

[AddPeriod.jsx] 날짜 형식 수정

---

src/components/add-product/AddPeriod.jsx

[AddPeriod.jsx] 기존 시간형식으로 변경

---

public/_redirects

[_redirects] 새로고침시 404 에러 해결

---

public/_redirects

[_redirects] 파일 삭제

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] json형식으로 수정

[ProductAddPage.jsx] json형식으로 수정

---

src/components/add-product/AddProductForm.jsx

[AddProductForm.jsx] string 형식으로 보내기

[AddProductForm.jsx] string 형식으로 보내기

---

src/components/add-product/AddProductForm.jsx
src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] string 형식으로 수정

[ProductAddPage.jsx] string 형식으로 수정

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] 폼데이터로 다시 변경

[ProductAddPage.jsx] 폼데이터로 다시 변경

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] blob 방식에서 수정

[ProductAddPage.jsx] blob 방식에서 수정

---

src/constants/AddProducts.jsx
src/pages/ProductAddPage.jsx

[ProductAddPage] 데이터 형식 수정, 인증토큰 헤더에 넣어서 보내기

[ProductAddPage] 데이터 형식 수정, 인증토큰 헤더에 넣어서 보내기

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] key값 변경

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] 수정

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] 에러메시지 세분화 및 폼데이터 출력

[ProductAddPage.jsx] 에러메시지 세분화 및 폼데이터 출력

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] product 객체, images 객체만 폼데이터로 보내기

[ProductAddPage.jsx] product 객체, images 객체만 폼데이터로 보내기

---

src/pages/ProductAddPage.jsx

[ProductAddPage.jsx] 기존으로 되돌리기

[ProductAddPage.jsx] 기존으로 되돌리기

---

src/components/main/ProductGrid.jsx
src/constants/ItemsPerPage.js

[MainPage] 이미지 렌더링 수정

---

src/App.jsx
src/components/detail/ProductInfo.jsx
src/components/mock-data/ImageGallery.jsx

[DetailPage] 데이터 렌더링-1

---

src/components/detail/ProductInfo.jsx
src/components/mock-data/ImageGallery.jsx

[DetailPage] 데이터 렌더링-2

---

src/pages/DetailPage.jsx

[DetailPage] 데이터 렌더링-3

---

src/components/user-profile/User.jsx

[User.jsx] 버튼태그로 변경

---

src/components/user-profile/UserProfile.jsx

[UserProfile.jsx] 회원정보 불러오는 api 요청

[UserProfile.jsx] 회원정보 불러오는 api 요청

---

src/pages/MainPage.jsx

[MainPage] 상품데이터 100개만 렌더링
